lsst/meas_base

doc/doxygen.conf.in
include/lsst/meas/base/Transform.h
python/lsst/meas/base/__init__.py
python/lsst/meas/base/base.py
python/lsst/meas/base/transforms.py
python/lsst/meas/base/wrappers.py
tests/SillyCentroid.h
tests/testTransform.py

Measurement algorithm plugins may now specify a "transformation" which will
convert their raw outputs into a calibrated form, suitable for database
ingestion etc.

Measurement transformation framework.

---

include/lsst/meas/base/SdssCentroid.h
src/SdssCentroid.cc
tests/testSdssCentroid.py

DM-1364 set specific MeasurementError's for SdssCentroidAlgorithm

---

python/lsst/meas/base/applyApCorr.py

Fixed the test that determined if the required models for flux
and fluxSigma were present in the aperture correction map.
The test incorrectly assumed that ApCorrMap.get raised an
exception if a field was missing; in fact it returns None.
Tested using a slightly hacked version of
meas_extensions_photometryKron tests/Kron.py
since we don't yet have a unit test for appling ap. corr.

ApplyApCorrTask.run: fix test for models in apCorrMap DM-3460

---

include/lsst/meas/base/FluxUtilities.h
python/lsst/meas/base/tests.py
src/ApertureFlux.cc
src/CentroidUtilities.cc
src/FluxUtilities.cc
src/SdssShape.cc
tests/testSdssShape.py

When transforming data to calibrated form for database ingest we should not
allow the process to be derailed by a negative flux measurement.

Review for DM-3483: don't throw when transforming negative fluxes

---

src/ApertureFlux.cc
src/Blendedness.cc
src/CircularApertureFlux.cc
src/SincCoeffs.cc

Makes the following replacements:
- boost::scoped_ptr -> std::unique_ptr
- boost::shared_ptr -> std::shared_ptr
- boost::weak_ptr -> std::weak_ptr
- boost::static_pointer_cast -> std::static_pointer_cast
- boost::dynamic_pointer_cast -> std::dynamic_pointer_cast
- boost::const_pointer_cast -> std::const_pointer_cast
- boost::reinterpret_pointer_cast -> std::reinterpret_pointer_cast
- boost::enamble_shared_from_this -> std::enable_shared_from_this
- boost pointer related includes -> standard library memory

DM-5879 Remove use of Boost smart pointers throughout the Science Pipelines

---

include/lsst/meas/base/FlagHandler.h
python/lsst/meas/base/flagDecorator.py
python/lsst/meas/base/utilities.i
src/FlagHandler.cc
tests/testFlagHandler.py

Add method to initialize FlagHandler with a vector of FlagDefinitions
Allow FlagDefinition to be constructed from a pair of strings
unit test testFlagHandler added

Changes to FlagHandler so that it can be used for Python only plugins

---

python/lsst/meas/base/__init__.py
python/lsst/meas/base/catalogCalculation.py
python/lsst/meas/base/classification.py
python/lsst/meas/base/forcedPhotImage.py
python/lsst/meas/base/pluginsBase.py
tests/testCatalogCalculation.py
tests/testClassification.py

To improve readability and limit ambiguity in function, afterburners
is renamed to catalogCalculation

Rename afterburner to catalogCalculation

---

src/CentroidUtilities.cc
src/GaussianCentroid.cc

Also cleans up some unusual code in `GaussianCentroid` that turned out not to be the problem.

DM-7753: Fail gracefully when CentroidChecker can't get a Peak.

---

python/lsst/meas/base/baseMeasurement.py
python/lsst/meas/base/forcedMeasurement.py
python/lsst/meas/base/sfm.py

This makes it available in the ForcedMeasurementTask as well as
SingleFrameMeasurementTask. Unfortunately, the actual measurement
iteration cannot live in BaseMeasurementTask because the forced
measurement requires iterating through two catalogs in sync, while
the single frame measurement only has one.

refactor undeblended measurement into BaseMeasurementTask

---

python/lsst/meas/base/baseLib.py
python/lsst/meas/base/forcedPhotImage.py

Without this import, the docstring created for `SdssCentroidTransform` uses C++ names for the parameter types rather than python names.

DM-8461: Wrap pipe_tasks with pybind11

---

include/lsst/meas/base/pybind11.h
python/lsst/meas/base/algorithm.cc

This change allows Algorithm classes to be passed to methods that expect a `SingleFrameAlgorithm`.

DM-8454: Wrap meas_extensions_shapeHSM with pybind11

---

tests/testVariance.py

This PSF width is used to index a NumPy array, which means — as of NumPy 1.12
— that it's required to be integral.

Review for DM-9316: tests broken with NumPy 1.12

---

python/lsst/meas/base/sdssShape.cc

Add wrappers for some methods apparently not used until meas_modelfit.

DM-8465: wrap meas_modelfit with pybind11

---

include/lsst/meas/base/ApertureFlux.h
include/lsst/meas/base/Blendedness.h
include/lsst/meas/base/FlagHandler.h
include/lsst/meas/base/GaussianCentroid.h
include/lsst/meas/base/GaussianFlux.h
include/lsst/meas/base/NaiveCentroid.h
include/lsst/meas/base/PeakLikelihoodFlux.h
include/lsst/meas/base/PsfFlux.h
include/lsst/meas/base/SdssCentroid.h
include/lsst/meas/base/SdssShape.h
python/lsst/meas/base/utilities.i
src/ApertureFlux.cc
src/Blendedness.cc
src/FlagHandler.cc
src/GaussianCentroid.cc
src/GaussianFlux.cc
src/InputUtilities.cc
src/NaiveCentroid.cc
src/PeakLikelihoodFlux.cc
src/PsfFlux.cc
src/ScaledApertureFlux.cc
src/SdssCentroid.cc
src/SdssShape.cc
tests/SillyCentroid.h
tests/testApertureFlux.py
tests/testCatalogCalculation.py
tests/testCentroidChecker.py
tests/testFlagHandler.py
tests/testPsfFlux.py
tests/testSdssShape.py

enum is replaced with static FlagDefinition of the same name
If the index of the flag is required a FlagDefinition.number
If the flag name is required, use FlagDefinition.name
Remove the old style of initializing the FlagHandler using iterator
to a std::array<FlagDefinition>.  A new class FlagDefinitionList
is introduced to specify the FlagDefinitions used to initialize the
FlagHandler.  Add flags to the FlagDefinitionList using the methods
addFailureFlag() and add(name, doc). When done, use the FlagHandler
initializer addFields(schema, name, flagDefinitionList).
An optional exclusion list exclDefs is provided if some members of
the algorithms FlagDefinitionList are not desired for a particular
configuration.  The _flagHandler keeps the same numbering of flags
whether or not a flag is …

DM-9249 Change FlagHandler to remove the enum of flag types

---

python/lsst/meas/base/forcedPhotImage.py

Remove a cast that is no longer needed because of this change in afw

DM-9764: SOURCE_IO_NO_FOOTPRINTS and related enums should be properly wrapped in pybind11

---

include/lsst/meas/base/Blendedness.h
python/lsst/meas/base/blendedness.cc
src/Blendedness.cc
tests/testBlendedness.py

This addresses three problems in the blendedness calculation:
- a simple transcription bug in what is now computeAbsExpectation (this is what originally spawened the ticket);
- the integral in what is now computeAbsExpectation was over a nonnormalized probability;
- we were truncating de-biased absolute values before summing them, which was introducing another bias we weren't correcting for.
I've also added some new unit tests.

DM-10237: fix errors in blendedness calculation

---

src/SdssCentroid.cc
src/SincCoeffs.cc

[DM-4639](https://jira.lsstcorp.org/browse/DM-4639) requires that `afw` components no longer have type members `Ptr` and `ConstPtr` representing shared pointers to those types. This is a breaking API change that requires changes to downstream code.
For clarity, no unnecessary changes changes were made to this package, not even a `clang-format` pass.

DM-4639: modernize afw code and reduce doxygen errors

---

examples/runSingleFrameTask.py
python/lsst/meas/base/applyApCorr.py
python/lsst/meas/base/baseMeasurement.py
python/lsst/meas/base/footprintArea.py
python/lsst/meas/base/forcedPhotCoadd.py
python/lsst/meas/base/noiseReplacer.py
python/lsst/meas/base/plugins.py
python/lsst/meas/base/sfm.py
python/lsst/meas/base/wrappers.py
setup.cfg
tests/test_ApCorrNameSet.py
tests/test_ApertureFlux.py
tests/test_PluginLogs.py
tests/test_centroid.py

Ensures that the dummy classes registered in one test are still valid so that a later test will not complain about them.
Also make flake8 clean and fix a couple of warnings. The remaining flake8 warnings are caused by Doxygen `##` syntax. @jonathansick I am assuming that they will be fixed as part of the migration to numpydoc.

DM-11539: Fix test for pytest and make flake8 clean

---

python/lsst/meas/base/forcedPhotCcd.py

Use of NAXIS1,NAXIS2 is being too familiar with the output format.
lsst.afw.image.bboxFromMetadata allows us to abstract the format.
This is especially important once we activate compression.

DM-11332: use bboxFromMetadata instead of NAXIS1,NAXIS2

---

python/lsst/meas/base/forcedPhotCoadd.py
python/lsst/meas/base/plugins.py
python/lsst/meas/base/wrappers.py
tests/test_InputCount.py
tests/test_Variance.py

And run it in forced coadd measurement.

DM-12243: make inputCount more robust

---

python/lsst/meas/base/forcedPhotCoadd.py

the same as for measureCoaddSources.

DM-9953: forcedPhotCoadd: configure PixelFlags

---

python/lsst/meas/base/forcedPhotCoadd.py
python/lsst/meas/base/forcedPhotImage.py

The size of the PSF cache can have a significant effect upon the runtime
for complicated PSF models. For coadds, CoaddPsf can be complicated.

DM-13854: forcedPhotCoadd: add command-line PSF cache configuration

---

python/lsst/meas/base/measurementInvestigationLib.py
tests/test_ApertureFlux.py

Use `getScalar` or `getArray` instead of deprecated `get`
on `PropertySet` and `PropertyList` instances.

DM-14842: Fix deprecation warnings from PropertyList/Set.get

---

doc/ReconstructingMeasurements.rst
python/lsst/meas/base/measurementInvestigationLib.py

Adds two options to makeRerunCatalog to either resetParents (default=True) to zero or addParents (default=False), so that child objects with parents outside of the rerunCatalog aren't skipped by runPlugins.

DM-14534: Fix measurementInvestigationLib.makeRerunCatalog parent keys

---

python/lsst/meas/base/forcedPhotImage.py

Rename methods according to RFC-352.
Fifteen total repositories with changes.

DM-2639: {{Standardize primary method names, run/runDataRef, across PipeTasks}}

---

python/lsst/meas/base/applyApCorr.py
tests/test_ApplyApCorr.py

Hard to test this, since the order could easily be right accidentally, but I've done what I could.

DM-16392: Ensure ApCorr fields are added in a deterministic order.

---

python/lsst/meas/base/forcedPhotCcd.py
python/lsst/meas/base/forcedPhotImage.py

The conversion of ForcedPhotCoadd was straightforward.  ForcedPhotCcd
required more handling, with duplicate operations in adjustArgsAndRun
to work around Gen-2 butler methods in the source filtering and
transformation code.

DM-17474: Convert ForcedPhotCcd and ForcedPhotCoadd into pipelineTasks.

---

python/lsst/meas/base/forcedPhotCcd.py
python/lsst/meas/base/forcedPhotImage.py

QuantumGraph generation does not yet support using component DatasetTypes as declared inputs or outputs; the changes here workaround this by declaring the full composite as the input and only loading one component.

DM-15843: fix for forced photometry PipelineTasks

---

python/lsst/meas/base/wrappers.py

Change default module to None 
Changing to None causes the module to be looked up from the
control class, as numerical lookup proved to be unreliable.

Tickets/DM-17757 Fix creating imports when saving config

---

tests/test_centroid.py

This PR fixes an incorrect import of `afw.detection` that was exposed by the changes in lsst/afw#476.

DM-20286: Modernize pybind11 wrappers for afw.table and afw.table.io

---

src/PeakLikelihoodFlux.cc

This PR replaces calls to `Kernel.getCtrX` and `getCtrY` with `getCtr`, and calls to `setCtrX` and `setCtrY` with `setCtr`.

DM-23651: ap_pipe calls some deprecated things

---

tests/test_GaussianFlux.py
tests/test_PsfFlux.py
tests/test_SdssCentroid.py

In a few unit tests, the signed deviation is checked against a positive number and the assertion is True if the deviation is lesser than the estimated uncertainty. The assertion would pass for large negative deviations, which the unit test is supposed to catch. The fixes in this PR take absolute value of the deviations before comparing to the estimated uncertainties.

DM-29767: Take absolute value of deviation to compare with uncertainty measures

---

python/lsst/meas/base/forcedPhotCcd.py

[Jira ticket](https://jira.lsstcorp.org/browse/DM-30046)
Jenkins run [#34305](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/34305/pipeline)

DM-30046: Defer reading refcats in forcedPhotCcd

---

python/lsst/meas/base/baseMeasurement.py

This is very similar to the changes made in DM-430. The plugins have different call signatures depending on whether they do logging internally or not. This was not accounted for 'undeblended' plugins.

DM-31442: Pass log to undeblended plugins

---

python/lsst/meas/base/forcedMeasurement.py
python/lsst/meas/base/sfm.py

The changes in the PR ensures that logging happens (at VERBOSE level) at least every 10 minutes (or at an interval that is configurable) when measurement is run.

DM-31528: Add more log messages to the measure task

---

python/lsst/meas/base/forcedPhotCcd.py
python/lsst/meas/base/plugins.py

Tasks seed forced photometry with ra/decl columns from
DataFrames instead of SourceCatalogs.

DM-31601: Add Tasks to force photometry from DataFrames

---

python/lsst/meas/base/tests.py

The `GaussianPsf` objects are position-independent and are not affected
by lack of position argument. However, with RFC-796 in mind, sensible
positions are passed.

DM-31869: Add sensible positions to computeShape in tests

---

README.rst
doc/conf.py
setup.cfg

Updates based on the latest updates in the package template (https://github.com/lsst/templates/tree/master/project_templates/stack_package)
- Add a basic README
- Update doc/conf.py for the documenteer 0.6 Sphinx configuration API

DM-30015: Update Sphinx conf.py for documenteer 0.6

---

python/lsst/meas/base/applyApCorr.py

This introduces some heartbeat logs in the aperture correction task, since it could take a couple of silent hours otherwise to finish the task.

DM-33854: Introduce heartbeat logs in ApplyApCorr

---

python/lsst/meas/base/forcedPhotCcd.py
python/lsst/meas/base/forcedPhotCoadd.py

DM-2850: Remove Task.getSchemaCatalogs

---

python/lsst/meas/base/forcedPhotCcd.py
tests/test_forcedPhot.py

Also added some trivial tests of the two tasks in forcedPhotCcd.py

DM-37058: Disable unnecessary measurements in CCD forced photometry

---

python/lsst/meas/base/baseMeasurement.py
tests/test_InvalidPsfFlag.py

This will set a catch-all flag in these cases as well as the invidual failure flags.

DM-44167: Add check for when plugins raise InvalidPsfError.

---

python/lsst/meas/base/diaCalculation.py

This PR merges some duplicate code in `DiaObjectCalculationTask`, and adds some logging to the outer execution loops of this sometimes long-running task.
Unfortunately, `git diff` badly garbled 8e97c3c because of the duplication; it may be easier to compare the [before](https://github.com/lsst/meas_base/blob/4d0e229738f3ec19994a3f2cdcf2d768a6da449d/python/lsst/meas/base/diaCalculation.py#L393) and [after](https://github.com/lsst/meas_base/blob/8e97c3c88b0f1c6114b05fade7f09bbaca922ac4/python/lsst/meas/base/diaCalculation.py#L393) repository states.

DM-43599: Add progress logs to DiaObjectCalculationTask

---

python/lsst/meas/base/baseMeasurement.py

This is particularly useful when there are multiple SingleFrameMeasurement subtasks, as it will now tell you which one had the failure.

DM-43593: Use FieldValidationError to improve error reporting for slots

---

python/lsst/meas/base/catalogCalculation.py

This PR fixes a bug in `CCContext` that caused it to intercept interrupts and treat them like algorithmic errors.

DM-45342: meas.base.CCContext suppresses all raisables, not just exceptions

---

src/SincCoeffs.cc

From v1.86 boost asserts that the bessel API is called with a positive value. Previously NaN was accepted. Now trap for NaN and return it before calling boost.

DM-45545: Trap NaN before calling boost API

---

python/lsst/meas/base/compensatedGaussian/_compensatedTophat.py
python/lsst/meas/base/diaCalculationPlugins.py
tests/test_diaCalculationPlugins.py

The solution I came up with is to create separate columns for each band rather than two columns populated with multi-element lists in each row.
I also updated the unit tests so that we are testing the multi-band version of Lomb-Scargle.
The plugin works now, but it is slow. I think this is simply because the Astropy Lomb-Scargle calculation is slow, and not a limitation of our pipelines code.

DM-48928: Fix serialization issue with LombScarglePeriodogramMulti plugin

---

python/lsst/meas/base/forcedPhotCcd.py

I'm marking this for removal after v29 because I expect it to be backported to v29, since this is a continuation of DM-49263.

DM-49452: Deprecate already-disabled includePhotoCalibVar option.
